// wMensajero.java
// Referencias:
// https://faq.whatsapp.com/general/chats/how-to-use-click-to-chat/?lang=es
//---------------------------------------------------------------------------
// Este programa fuente informático se acoge a la licencia GNU GPL v3
// https://www.gnu.org/licenses/gpl-3.0.en.html
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see https://www.gnu.org/licenses/
//----------------------------------------------------------------------------------

// Paquete cliente que contiene a programa wMensajero.java
package cliente;

import java.awt.Point;
import java.awt.Rectangle;
import java.io.IOException;
import java.io.StringWriter;

import javax.swing.*;

/** La clase <b>wMensajero</b>
 * consiste en un formulario con opciones para enviar mensajes de textos a un teléfono celular
 * mediante el servicio de whatsapp.com<br>
 * <b>Referencias:</b><br>
 * Centro de ayuda de WhatsApp: <a href="https://faq.whatsapp.com/general/chats/how-to-use-click-to-chat/?lang=es" target="_blank">Cómo usar el clic para chatear.</a><br>
 * <b>Fecha:</b><br>21-Mayo-2021
 * @author Octulio Biletán
 * @version 1.0
 */
public class wMensajero extends javax.swing.JFrame 
{
    JPanel ultimo_seleccionado;

    /**
     * Examina 'nro' si contiene una secuencia numérica.
     * @param nro Secuencia de caracteres numéricos a examinar.
     * @return Devuelve 'true' si todos los caracteres en 'nro' son numéricos sino 'false'.
     */
    boolean cnum(String nro) 
    {
        if(nro.isEmpty() == true)
            return false;  // no contiene ningún caracter
        
        char secuencia[] = nro.toCharArray();
        boolean contiene_nro = false;
        
        for(int i = 0; i < secuencia.length; i++)
        {
            if(secuencia[i] >= '0' && secuencia[i] <= '9')
              contiene_nro = true;
            else
            {    
              contiene_nro = false;  
              break;
            }  
        }
        
        return contiene_nro;
    }
    
    /** Ejecuta el proceso con sus argumentos indicado en 'arg'
     * y no espera su finalización.
     * @param arg Contiene una lista de argumentos de longitud variable.
     * @return Devuelve el estado del proceso.
     * @throws IOException Excepción por error E/S.
     * @throws InterruptedException Excepción por interrupción.
     */
    int proceso(String... arg) throws IOException, InterruptedException
    {
        Process p;
        p = new ProcessBuilder(arg).inheritIO().start();
        return p.exitValue();
    }

    /** Este método envía la 'url' al navegador que se ha seleccionado
     * y se invoca a proceso() para su ejecución.<br>
     * <b>Ejemplo:</b><br>
     * int estado = navegador("https://www.google.com/search?q=tortilla&sourceid=chrome&ie=UTF-8");
     * @param url Contiene la línea de textos que se pasa al navegador.
     * @return Devuelve el estado del proceso.
     * @throws java.io.IOException Excepción por error E/S.
     * @throws java.lang.InterruptedException Excepción por interrupción.
     */
    int navegador(String url) throws IOException, InterruptedException 
    {
        String aplic = lblNavSele.getText();
        
        return proceso(aplic, url);
    }
    
    /** wMensajero crea un nuevo formulario. */
    public wMensajero() 
    {
        Point pt = new Point();
        Rectangle rg = new Rectangle();
        
        initComponents();
        pt = pnlPrefs.getLocation(pt);
        rg = pnlPrefs.getBounds();
        
        pnlContactos.setBounds(pt.x, pt.y, rg.width, rg.height);
        add(pnlContactos);
        
        pnlMensajes.setBounds(rg);
        add(pnlMensajes);
        
        pnlEnviarMensaje.setBounds(rg);
        add(pnlEnviarMensaje);
        
        pnlPrefs.setVisible(false);
        pnlContactos.setVisible(false);
        pnlMensajes.setVisible(false);
        pnlEnviarMensaje.setVisible(false);
        
        ultimo_seleccionado = null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        dlgSeleNav = new javax.swing.JFileChooser();
        pnlContactos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContactos = new javax.swing.JTable();
        lblDirContactos = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        pnlMensajes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cajaTextoRedactado = new javax.swing.JTextArea();
        btnLimpiar = new javax.swing.JButton();
        btnMsjAceptar = new javax.swing.JButton();
        pnlEnviarMensaje = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cajaTextoMensaje = new javax.swing.JTextArea();
        txtTelCelular = new javax.swing.JTextField();
        btnEnviarMensaje = new javax.swing.JButton();
        btnEMCancelar = new javax.swing.JButton();
        tbBarraPrincipal = new javax.swing.JToolBar();
        btnContactos = new javax.swing.JButton();
        btnNMensaje = new javax.swing.JButton();
        btnEMensaje = new javax.swing.JButton();
        btnPrefs = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        pnlPrefs = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtLongMaxima = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLongMinima = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnPrefsAceptar = new javax.swing.JButton();
        btnPrefsCancelar = new javax.swing.JButton();
        btnPaloma = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblNavSele = new javax.swing.JLabel();
        btnCambiar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        dlgSeleNav.setAcceptAllFileFilterUsed(false);
        dlgSeleNav.setCurrentDirectory(new java.io.File("/usr/bin"));
        dlgSeleNav.setDialogTitle("Seleccionar navegador");
        dlgSeleNav.setSelectedFile(new java.io.File("/usr/bin/firefox"));
        dlgSeleNav.getAccessibleContext().setAccessibleParent(this);

        pnlContactos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblContactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ponga aquí su nombre", "5491231123456", "nombre@servicio.com"},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Teléfono", "C-Electr"
            }
        ));
        tblContactos.setToolTipText("Su agenda de contactos.");
        tblContactos.setCellSelectionEnabled(true);
        tblContactos.setSelectionBackground(new java.awt.Color(152, 204, 152));
        tblContactos.setSelectionForeground(new java.awt.Color(1, 1, 1));
        jScrollPane1.setViewportView(tblContactos);
        if (tblContactos.getColumnModel().getColumnCount() > 0) {
            tblContactos.getColumnModel().getColumn(0).setHeaderValue("Nombre");
            tblContactos.getColumnModel().getColumn(1).setHeaderValue("Teléfono");
            tblContactos.getColumnModel().getColumn(2).setHeaderValue("C-Electr");
        }

        lblDirContactos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDirContactos.setText("Contactos");
        lblDirContactos.setBorder(javax.swing.BorderFactory.createTitledBorder("Directorio"));
        lblDirContactos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblDirContactos.setIconTextGap(1);
        lblDirContactos.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(74, 24));
        btnCancelar.setMinimumSize(new java.awt.Dimension(74, 24));
        btnCancelar.setPreferredSize(new java.awt.Dimension(74, 24));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.setMaximumSize(new java.awt.Dimension(74, 24));
        btnAceptar.setMinimumSize(new java.awt.Dimension(74, 24));
        btnAceptar.setPreferredSize(new java.awt.Dimension(74, 24));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlContactosLayout = new javax.swing.GroupLayout(pnlContactos);
        pnlContactos.setLayout(pnlContactosLayout);
        pnlContactosLayout.setHorizontalGroup(
            pnlContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContactosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlContactosLayout.createSequentialGroup()
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblDirContactos, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContactosLayout.setVerticalGroup(
            pnlContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContactosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDirContactos)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlContactos.getAccessibleContext().setAccessibleParent(this);

        pnlMensajes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cajaTextoRedactado.setColumns(20);
        cajaTextoRedactado.setRows(5);
        cajaTextoRedactado.setBorder(javax.swing.BorderFactory.createTitledBorder("Escriba su mensaje"));
        jScrollPane2.setViewportView(cajaTextoRedactado);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setMaximumSize(new java.awt.Dimension(74, 24));
        btnLimpiar.setMinimumSize(new java.awt.Dimension(74, 24));
        btnLimpiar.setPreferredSize(new java.awt.Dimension(74, 24));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnMsjAceptar.setText("Aceptar");
        btnMsjAceptar.setMaximumSize(new java.awt.Dimension(74, 24));
        btnMsjAceptar.setMinimumSize(new java.awt.Dimension(74, 24));
        btnMsjAceptar.setPreferredSize(new java.awt.Dimension(74, 24));
        btnMsjAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMsjAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMensajesLayout = new javax.swing.GroupLayout(pnlMensajes);
        pnlMensajes.setLayout(pnlMensajesLayout);
        pnlMensajesLayout.setHorizontalGroup(
            pnlMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMensajesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addGroup(pnlMensajesLayout.createSequentialGroup()
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMsjAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlMensajesLayout.setVerticalGroup(
            pnlMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMensajesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnlMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMsjAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlEnviarMensaje.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cajaTextoMensaje.setEditable(false);
        cajaTextoMensaje.setColumns(20);
        cajaTextoMensaje.setRows(5);
        cajaTextoMensaje.setBorder(javax.swing.BorderFactory.createTitledBorder("Mensaje a enviar"));
        jScrollPane3.setViewportView(cajaTextoMensaje);

        txtTelCelular.setEditable(false);
        txtTelCelular.setToolTipText("Número de teléfono de celular seleccionado.");
        txtTelCelular.setBorder(javax.swing.BorderFactory.createTitledBorder("Teléfono celular"));

        btnEnviarMensaje.setText("Enviar mensaje");
        btnEnviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarMensajeActionPerformed(evt);
            }
        });

        btnEMCancelar.setText("Cancelar");
        btnEMCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEMCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEnviarMensajeLayout = new javax.swing.GroupLayout(pnlEnviarMensaje);
        pnlEnviarMensaje.setLayout(pnlEnviarMensajeLayout);
        pnlEnviarMensajeLayout.setHorizontalGroup(
            pnlEnviarMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnviarMensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEnviarMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(txtTelCelular))
                .addGap(18, 18, 18)
                .addGroup(pnlEnviarMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEnviarMensaje)
                    .addComponent(btnEMCancelar))
                .addContainerGap(419, Short.MAX_VALUE))
        );
        pnlEnviarMensajeLayout.setVerticalGroup(
            pnlEnviarMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnviarMensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlEnviarMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlEnviarMensajeLayout.createSequentialGroup()
                        .addComponent(btnEnviarMensaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEMCancelar)))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paloma Mensajera");

        tbBarraPrincipal.setFloatable(false);
        tbBarraPrincipal.setOrientation(javax.swing.SwingConstants.VERTICAL);
        tbBarraPrincipal.setRollover(true);

        btnContactos.setText("Contactos");
        btnContactos.setFocusable(false);
        btnContactos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContactos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactosActionPerformed(evt);
            }
        });
        tbBarraPrincipal.add(btnContactos);

        btnNMensaje.setText("Nuevo mensaje");
        btnNMensaje.setFocusable(false);
        btnNMensaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNMensaje.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNMensajeActionPerformed(evt);
            }
        });
        tbBarraPrincipal.add(btnNMensaje);

        btnEMensaje.setText("Enviar Mensaje");
        btnEMensaje.setFocusable(false);
        btnEMensaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEMensaje.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEMensajeActionPerformed(evt);
            }
        });
        tbBarraPrincipal.add(btnEMensaje);

        btnPrefs.setText("Preferencias");
        btnPrefs.setFocusable(false);
        btnPrefs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrefs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPrefs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrefsActionPerformed(evt);
            }
        });
        tbBarraPrincipal.add(btnPrefs);

        btnSalir.setText("Salir");
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        tbBarraPrincipal.add(btnSalir);

        pnlPrefs.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Longitud máxima del mensaje:");

        txtLongMaxima.setText("240");
        txtLongMaxima.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLongMaxima.setMaximumSize(new java.awt.Dimension(48, 30));
        txtLongMaxima.setMinimumSize(new java.awt.Dimension(48, 30));
        txtLongMaxima.setPreferredSize(new java.awt.Dimension(48, 30));

        jLabel2.setText("Longitud mínima del mensaje:");

        txtLongMinima.setText("1");
        txtLongMinima.setMaximumSize(new java.awt.Dimension(48, 30));
        txtLongMinima.setMinimumSize(new java.awt.Dimension(36, 20));

        jLabel3.setText("caracteres");

        jLabel4.setText("caracteres");

        btnPrefsAceptar.setText("Aceptar");
        btnPrefsAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrefsAceptarActionPerformed(evt);
            }
        });

        btnPrefsCancelar.setText("Cancelar");
        btnPrefsCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrefsCancelarActionPerformed(evt);
            }
        });

        btnPaloma.setBorder(null);
        btnPaloma.setBorderPainted(false);
        btnPaloma.setDefaultCapable(false);

        jLabel5.setText("Navegador predeterminado");
        jLabel5.setFocusable(false);

        lblNavSele.setText("/usr/bin/firefox");

        btnCambiar.setText("Cambiar");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/pamesj.png"))); // NOI18N
        jButton1.setBorderPainted(false);

        javax.swing.GroupLayout pnlPrefsLayout = new javax.swing.GroupLayout(pnlPrefs);
        pnlPrefs.setLayout(pnlPrefsLayout);
        pnlPrefsLayout.setHorizontalGroup(
            pnlPrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrefsLayout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPaloma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlPrefsLayout.createSequentialGroup()
                        .addGroup(pnlPrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrefsLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(btnCambiar))
                            .addGroup(pnlPrefsLayout.createSequentialGroup()
                                .addComponent(btnPrefsAceptar)
                                .addGap(18, 18, 18)
                                .addComponent(btnPrefsCancelar))
                            .addComponent(lblNavSele, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlPrefsLayout.createSequentialGroup()
                        .addGroup(pnlPrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrefsLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLongMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrefsLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLongMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32))))
        );
        pnlPrefsLayout.setVerticalGroup(
            pnlPrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrefsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrefsLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlPrefsLayout.createSequentialGroup()
                        .addComponent(btnPaloma)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlPrefsLayout.createSequentialGroup()
                        .addGroup(pnlPrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtLongMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(9, 9, 9)
                        .addGroup(pnlPrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtLongMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(btnCambiar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNavSele)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrefsAceptar)
                            .addComponent(btnPrefsCancelar))
                        .addGap(234, 234, 234))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbBarraPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlPrefs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbBarraPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlPrefs, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        dispose();
        System.exit(0);

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnPrefsAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrefsAceptarActionPerformed

        pnlPrefs.setVisible(false);
        invalidate();

    }//GEN-LAST:event_btnPrefsAceptarActionPerformed

    private void btnPrefsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrefsActionPerformed

        if(ultimo_seleccionado != null)
        {
            ultimo_seleccionado.setVisible(false);
            ultimo_seleccionado.setEnabled(false);
            ultimo_seleccionado.invalidate();
        }    

        pnlPrefs.setVisible(true);
        pnlPrefs.requestFocusInWindow();
        pnlPrefs.revalidate();
        ultimo_seleccionado = pnlPrefs;
        
    }//GEN-LAST:event_btnPrefsActionPerformed

    private void btnPrefsCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrefsCancelarActionPerformed

        pnlPrefs.setVisible(false);
        invalidate();
        
    }//GEN-LAST:event_btnPrefsCancelarActionPerformed

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        int estado;
        
        estado = dlgSeleNav.showOpenDialog(this);
        if(estado == JFileChooser.APPROVE_OPTION)
          lblNavSele.setText(dlgSeleNav.getSelectedFile().getAbsolutePath());

    }//GEN-LAST:event_btnCambiarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        pnlContactos.setVisible(false);
        pnlContactos.invalidate();
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactosActionPerformed

        if(ultimo_seleccionado != null)
        {
            ultimo_seleccionado.setVisible(false);
            ultimo_seleccionado.setEnabled(false);
            ultimo_seleccionado.invalidate();
        }

        pnlContactos.setVisible(true);
        pnlContactos.requestFocusInWindow();
        pnlContactos.revalidate();
        
        ultimo_seleccionado = pnlContactos;
        
    }//GEN-LAST:event_btnContactosActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        pnlContactos.setVisible(false);
        pnlContactos.invalidate();
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        cajaTextoRedactado.setText("");
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnMsjAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMsjAceptarActionPerformed

        pnlMensajes.setVisible(false);
        pnlMensajes.invalidate();
        
    }//GEN-LAST:event_btnMsjAceptarActionPerformed

    private void btnNMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNMensajeActionPerformed
        
        if(ultimo_seleccionado != null)
        {
            ultimo_seleccionado.setVisible(false);
            ultimo_seleccionado.setEnabled(false);
            ultimo_seleccionado.invalidate();
        }
        
        pnlMensajes.setVisible(true);
        pnlMensajes.requestFocusInWindow();
        pnlMensajes.revalidate();
        ultimo_seleccionado = pnlMensajes;
        
    }//GEN-LAST:event_btnNMensajeActionPerformed

    private void btnEMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEMensajeActionPerformed
    // Evento botón "Enviar Mensaje" que muestra el panel "Enviar Mensaje"

        if(ultimo_seleccionado != null)
        {
            ultimo_seleccionado.setVisible(false);
            ultimo_seleccionado.setEnabled(false);
            ultimo_seleccionado.invalidate();
        }    

        pnlEnviarMensaje.setVisible(true);
        pnlEnviarMensaje.requestFocusInWindow();
        pnlEnviarMensaje.revalidate();

        cajaTextoMensaje.setText(cajaTextoRedactado.getText());
        
        int co = tblContactos.getSelectedColumn();
        int fi = tblContactos.getSelectedRow();
        if(co == -1 || fi == -1)
        {  
            co = 1;
            fi = 0;
        }
        
        String dato = (String)tblContactos.getValueAt(fi, co);
        txtTelCelular.setText(dato);

        ultimo_seleccionado = pnlEnviarMensaje;
        
    }//GEN-LAST:event_btnEMensajeActionPerformed

    private void btnEMCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEMCancelarActionPerformed
    // Evento botón "Cancelar" que cancela el envío del mensaje.
        
        JOptionPane.showMessageDialog(this, "Acción cancelada.");

        pnlEnviarMensaje.setVisible(false);
        pnlEnviarMensaje.invalidate();
        
    }//GEN-LAST:event_btnEMCancelarActionPerformed

    private void btnEnviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarMensajeActionPerformed
    // Evento botón "Enviar Mensaje" que invoca al navegador de páginas.
        String url_texto;
        String texto;
        StringWriter salida;
        
        if(cajaTextoMensaje.getText().length() < Integer.parseInt(txtLongMinima.getText()) || cajaTextoMensaje.getText().length() > Integer.parseInt(txtLongMaxima.getText()))
        {    
            salida = new StringWriter(1024);
            salida.write("Aviso:\nLongitud del mensaje ingresado: " + cajaTextoMensaje.getText().length() 
                         + "\nEscriba un mensaje de textos entre " + txtLongMinima.getText() + " y " + txtLongMaxima.getText() + " caracteres.");
            salida.flush();
                
            JOptionPane.showMessageDialog(this, salida);
            pnlEnviarMensaje.setVisible(false);
            pnlEnviarMensaje.invalidate();
            return;
        }

        if(cnum(txtTelCelular.getText()) == false)
        {    
            salida = new StringWriter(1024);
            salida.write("Aviso: El número de teléfono es incorrecto.\nCorrija en Contactos.");
            salida.flush();
            
            JOptionPane.showMessageDialog(this, salida);
            pnlEnviarMensaje.setVisible(false);
            pnlEnviarMensaje.invalidate();
            return;
        }

        texto = cajaTextoMensaje.getText().replace(" ", "+");
        texto = texto.replace("\n", "%0D");

        // Compone la URL completa para enviar el mensaje a través del servicio WhatsApp Web.
        url_texto = "https://api.whatsapp.com/send/?phone=" + txtTelCelular.getText() + "&text=" + texto + "&app_absent=0";

        // Abre el navegador de páginas web para enviar el mensaje de textos al nº de celular que se le indica
        // y usa el servicio de whatsapp web.
        try 
        {
            navegador(url_texto);
        }
        catch (IOException | InterruptedException ex) 
        {
            // Muestra los mensajes de errores capturados por la clase IOException o InterruptedException
            System.err.println("- Error importante -");
            System.err.println(ex.getMessage());
            
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error importante", JOptionPane.ERROR_MESSAGE);
            pnlEnviarMensaje.setVisible(false);
            pnlEnviarMensaje.invalidate();
            return;
        }
        catch(IllegalThreadStateException ex2)
        {
            System.err.println("- Aviso importante -");
            System.err.println(ex2.getMessage());

            JOptionPane.showMessageDialog(this, "Se encuentra abierto el navegador", "Aviso importante", JOptionPane.INFORMATION_MESSAGE);
            pnlEnviarMensaje.setVisible(false);
            pnlEnviarMensaje.invalidate();
            return;
        }

        JOptionPane.showMessageDialog(this, "¡Listo!");

        pnlEnviarMensaje.setVisible(false);
        pnlEnviarMensaje.invalidate();

    }//GEN-LAST:event_btnEnviarMensajeActionPerformed

    /**
     * Función principal de entrada a la clase wMensajero.
     * @param args lista de argumentos que vienen de la línea de comandos.
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util
                .logging
                .Logger
                .getLogger(wMensajero.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util
                .logging
                .Logger
                .getLogger(wMensajero.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util
                .logging
                .Logger
                .getLogger(wMensajero.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util
                .logging
                .Logger
                .getLogger(wMensajero.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable() {
                public void run() {
                    new wMensajero().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnContactos;
    private javax.swing.JButton btnEMCancelar;
    private javax.swing.JButton btnEMensaje;
    private javax.swing.JButton btnEnviarMensaje;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMsjAceptar;
    private javax.swing.JButton btnNMensaje;
    private javax.swing.JButton btnPaloma;
    private javax.swing.JButton btnPrefs;
    private javax.swing.JButton btnPrefsAceptar;
    private javax.swing.JButton btnPrefsCancelar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextArea cajaTextoMensaje;
    private javax.swing.JTextArea cajaTextoRedactado;
    private javax.swing.JFileChooser dlgSeleNav;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDirContactos;
    private javax.swing.JLabel lblNavSele;
    private javax.swing.JPanel pnlContactos;
    private javax.swing.JPanel pnlEnviarMensaje;
    private javax.swing.JPanel pnlMensajes;
    private javax.swing.JPanel pnlPrefs;
    private javax.swing.JToolBar tbBarraPrincipal;
    private javax.swing.JTable tblContactos;
    private javax.swing.JTextField txtLongMaxima;
    private javax.swing.JTextField txtLongMinima;
    private javax.swing.JTextField txtTelCelular;
    // End of variables declaration//GEN-END:variables
}
