#!/bin/sh
# luces
# Eugenio Martinez - febrero de 2003
# Prende/apaga las luces del teclado
# Ultima actualización: vie 31 dic 2021 14:35:01 -ART
/usr/bin/setleds -D +num +caps +scroll ; sleep 2 ; /usr/bin/setleds -D -num -caps -scroll
