#!/bin/bash
# Utilidades Torrente, edición Febrero 2025.
# Octulio Biletán <octulioBiletan@telegram>
#

# Puede ser dialog, cdialog, whiptail (newt), zenity, kdialog, etc...
VTEXTO=`command -v dialog`

# Directorio base de las Utilidades Torrente.
base=/base

PATH=$base/programa:$PATH
TIEMPO=`echo "[";date;echo $(timedatectl|grep zone:);echo "]"`
OSLINUX=
if [ -f /etc/os-release ]; then
    . /etc/os-release
    if [ -n "$PRETTY_NAME" ]; then
	VEROS="$PRETTY_NAME"
    else
	VEROS="$NAME"
    fi
fi

# Elimina de la memoria otras instancias de menú.bin
eliminamenu()
{
	for opmen in $(pgrep menú.bin); do
	  kill -n 9 $opmen
	  kill -n 9 menú
	  kill -n 9 dialog
	  kill -n 9 cdialog
	  kill -n 9 whiptail
	done
}

# Informa el nº de versión de 'menú'
versionMenu()
{
    echo "Versión: 1.2.2025"
}

# Borra el archivo de la unidad de disco vigente
# Uso: borrarArchivo nombre_archivo_borrar.ext
borrarArchivo()
{
if [ $# -gt 0 ] ; then
    echo -n -e "\b" > $1
    unlink $1
else
    echo "borrarArchivo(): falta argumento."
fi
}

# Visualiza una ayuda en pantalla
ayudaMenu()
{
    echo -e "< Descripción >\n" \
         "El comando 'menú' muestra en pantalla un menú de diez opciones.\n"\
         "Las opciones del menú principal están definidas en 'menú.bin'.\n"\
         "La finalidad de este comando es facilitar al usuario novel a que se\n"\
         "familiarice con el entorno Linux y la consola de textos 'bash'.\n"\
         "El comando 'menú.bin' se apoya principalmente en el comando '/bin/dialog'.\n"\
         "Existen otros comandos similares que pueden ser invocados: cdialog y whiptail.\n"\
         "Puede personalizar en 'menú' qué comando invocar según gustos personales.\n"\
         "Para tal fin tiene que modificar la variable 'VTEXTO='.\n"\
         "Los comandos 'menú' y 'menú.bin' forman parte de\n"\
         "Utilidades Torrente, edición Febrero 2025.\n\n"\
         "< Opciones admitidas >\n"\
         "Solicitar Ayuda:\n"\
         "\t--ayuda, -a, --help, -h\n"\
         "Conocer el nº de versión:\n"\
         "\t--version, -v\n" > salida.menu.ayuda
    $VTEXTO --title "Ayuda" --textbox salida.menu.ayuda 0 0
    borrarArchivo salida.menu.ayuda
}

eliminamenu

export base PATH TIEMPO VTEXTO

_error=1
if [ $# -gt 0 ] ; then
    # Examina por el arg. '--ayuda'...
    if [ "$1" = "--ayuda" ] || [ "$1" = "-a" ] || [ "$1" = "--help" ] || [ "$1" = "-h" ] ; then
	ayudaMenu
	_error=0
    fi

    # Examina por el arg. '--version' ó '-v'
    if [ "$1" = "--version" ] || [ "$1" = "-v" ] ; then
	echo $0
        versionMenu
	echo
        echo $VTEXTO
        $VTEXTO --version
        echo "Sistema operativo: "$VEROS
        _error=0
    else
	if [ "$_error" = "1" ] ; then
	    echo "Opción no admitida."
    	    echo "Escriba: menú -a ó menú -h para conocer las opciones admitidas."
    	fi
    fi

    exit $_error
fi

source menú.bin
retval=$?

case $retval in
  2)
    . $HOME/.bash_logout
    exit $retval;;
  1)
    break & clear;;
  255)
    break & clear;;
esac

exit 0
